In [ ]:
##Section A: Data Structures & Control Structures
#1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.
a=[3,69,80,54,32]
print(a)
a.append(102)
print(a)
a.extend([202])
print(a)
a.insert(5,6)
print(a)
a.remove(54)
print(a)
a.pop(6)
print(a)
a.clear()
print(a)
a=[5,2,3,4,4]
print(a)
print(a.index(3))
print(a.count(7))
a.sort()
print(a)
a.reverse()
print(a)

[3, 69, 80, 54, 32]
[3, 69, 80, 54, 32, 102]
[3, 69, 80, 54, 32, 102, 202]
[3, 69, 80, 54, 32, 6, 102, 202]
[3, 69, 80, 32, 6, 102, 202]
[3, 69, 80, 32, 6, 102]
[]
[5, 2, 3, 4, 4]
2
0
[2, 3, 4, 4, 5]
[5, 4, 4, 3, 2]


In [ ]:
#2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.
names=('Afrin','Sajju','Irfan')
print(names)
names[1]='Ammu'
print(names)

('Afrin', 'Sajju', 'Irfan')


TypeError: 'tuple' object does not support item assignment

The error TypeError: 'tuple' object does not support item assignment means you cannot change individual items within a tuple directly. Tuples are immutable, so you have to create a new tuple if you want different content.

In [ ]:
#3.	Create a set of integers with some duplicate values. Print the set and explain the output.
a={12,45,67,98,99,67,54,45}
print(a)

{98, 67, 99, 54, 12, 45}


In stes they can not allo the duplicated values and follo the unorder.For example in my set i have pass the some duplicated values but the final result is like this.The set can not allowes the duplicated values.

In [5]:
#4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.
a={'name':'Afrin','age':22,'city':'Kadapa'}
#In dict add the new keys or upadated the any values we use only udate() function only
a.update({'age':23})
a.update({'email':'afrinshaik7702@gmail.com'})
print(a)

{'name': 'Afrin', 'age': 23, 'city': 'Kadapa', 'email': 'afrinshaik7702@gmail.com'}


In [6]:
#Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.
age=int(input("Enter your age:"))
if age>=18:
    print("we are eligible for vote")
else:
    print("not eligible for vote")

Enter your age:15
not eligible for vote


In [9]:
'''6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail' '''
marks=int(input("enter your marks:"))
if marks>=90:
  print("grade:A")
elif marks<=89 and marks>=75:
  print("grade:B")
elif marks<=74 and marks>=50:
  print("grade:C")
else:
  print("Fail")


enter your marks:99
grade:A


In [14]:
#7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.
a=int(input("enter your number:"))
if a>0:
  if a%2==0:
      print('positive and even')
  elif a%2!=0:
     print("positive and odd")
  elif a==0:
    print('zero')
else:
  print('negative')

enter your number:3
positive and odd


In [25]:
##Section B: Numpy
'''8. Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10'''
import numpy as np
# Create a scalar
scalar_array = np.array(5)
print("Scalar array:", scalar_array)
# Create a 1D array with values 1 to 5
# np.arange(start, stop) generates numbers up to, but not including stop
array = np.arange(1, 6)
print("1D array:", array)
# Create a 2D array (2x3) with values from 10 to 60 in steps of 10
array = np.arange(10, 70, 10).reshape(2,3)
print("2D array:\n", array)

Scalar array: 5
1D array: [1 2 3 4 5]
2D array:
 [[10 20 30]
 [40 50 60]]


In [38]:
#9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().
import numpy as np
array=np.random.randint(0,101,size=(4,4))
print(array)

[[39 71 60 75]
 [63 23 85 29]
 [32 16 93 63]
 [87 73 14 80]]


In [45]:
#10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.
import numpy as np
import pandas as pd
array=np.arange(0,9).reshape(3,3)
print(array)
pd.DataFrame(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


,0,1,2
0,0,1,2
1,3,4,5
2,6,7,8


In [94]:
#Section C: Exploring Pandas
'''11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows'''
import pandas as pd
import numpy as np
data={'name':['Afrin','sajju','irfan','lahari','narendra','haritha','sadiya','divya','shabbu','shaheena','Faridha'],'Age':[22,23,47,45,35,42,44,50,20,40,55],'city':['kadapa','puttur','chennai','pulivendula','dharmavaram','kadapa','hyderbad','vizag','tirupathi','karnool','nellor'],'salary':[40000,20000,60000,None,30000,70000,40000,50000,60000,70000,80000]}
print(data)
df=pd.DataFrame(data)
print(df)
#Use .info()
a=df.info()
print(a)
#Use .describe()
b=df.describe()
print(b)
#Select 'Name' and 'City' columns
c=df[['name','city']]
print(c)
#Drop 'City' column
d=df.drop(columns=['city'])
print(d)
#Fill any missing values in 'Salary' column with the mean
e=df['salary'].mean()
print(e)
e=df['salary'].fillna(e)
print(e)
#Remove any duplicate rows
df.duplicated()
print(df.duplicated())

{'name': ['Afrin', 'sajju', 'irfan', 'lahari', 'narendra', 'haritha', 'sadiya', 'divya', 'shabbu', 'shaheena', 'Faridha'], 'Age': [22, 23, 47, 45, 35, 42, 44, 50, 20, 40, 55], 'city': ['kadapa', 'puttur', 'chennai', 'pulivendula', 'dharmavaram', 'kadapa', 'hyderbad', 'vizag', 'tirupathi', 'karnool', 'nellor'], 'salary': [40000, 20000, 60000, None, 30000, 70000, 40000, 50000, 60000, 70000, 80000]}
        name  Age         city   salary
0      Afrin   22       kadapa  40000.0
1      sajju   23       puttur  20000.0
2      irfan   47      chennai  60000.0
3     lahari   45  pulivendula      NaN
4   narendra   35  dharmavaram  30000.0
5    haritha   42       kadapa  70000.0
6     sadiya   44     hyderbad  40000.0
7      divya   50        vizag  50000.0
8     shabbu   20    tirupathi  60000.0
9   shaheena   40      karnool  70000.0
10   Faridha   55       nellor  80000.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column  Non-N